require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6.2
  Exclude:
    - db/schema.rb
    - bin/**/*
    - client/**/*
    - public/**/*
    - script/**/*
    - vendor/**/*
    - node_modules/**/*

Bundler/OrderedGems:
  Enabled: false

Layout/ConditionPosition:
  Enabled: false
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/LeadingCommentSpace:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*
Lint/AmbiguousOperator:
  Enabled: false
Lint/AmbiguousRegexpLiteral:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
Lint/DeprecatedClassMethods:
  Enabled: false
Lint/ElseLayout:
  Enabled: false
Lint/FlipFlop:
  Enabled: false
Lint/LiteralAsCondition:
  Enabled: false
Lint/LiteralInInterpolation:
  Enabled: false
Lint/Loop:
  Enabled: false
Lint/ParenthesesAsGroupedExpression:
  Enabled: false
Lint/RequireParentheses:
  Enabled: false
Lint/UnderscorePrefixedVariableName:
  Enabled: false
Lint/Void:
  Enabled: false

Metrics/AbcSize:
  Max: 20
Metrics/BlockLength:
  Exclude:
    - app/admin/**/*
    - lib/tasks/**/*
    - spec/**/*
  ExcludedMethods:
    - context
    - describe
    - it
    - xit
    - xfeature
    - xscenario
    - xcontext
    - shared_examples
    - shared_examples_for
    - scenario
    - feature
    - namespace
    - resource
    - patch
    - get
    - post
    - put
    - delete
    - head
    - example
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Enabled: true
  Max: 120
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
Naming/AsciiIdentifiers:
  Enabled: false
Naming/BinaryOperatorParameterName:
  Enabled: false
Naming/ConstantName:
  Description: Constants should use SCREAMING_SNAKE_CASE.
  Enabled: true
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#screaming-snake-case'
Naming/FileName:
  Enabled: false
Naming/PredicateName:
  ForbiddenPrefixes:
    - is_
Naming/RescuedExceptionsVariableName:
  PreferredName: exception

Rails:
  Enabled: true
Rails/ActionFilter:
  Enabled: true
  EnforcedStyle: action
Rails/Delegate:
  Enabled: false
Rails/SkipsModelValidations:
  Whitelist:
    - increment!
Rails/UnknownEnv:
  Environments:
    - test
    - development
    - staging
    - review
    - production

Style/Alias:
  Enabled: false
Style/ArrayJoin:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/Attr:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Style/CharacterLiteral:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: nested
Style/ClassVars:
  Enabled: false
Style/CollectionMethods:
  Enabled: false
Style/ColonMethodCall:
  Enabled: false
Style/CommentAnnotation:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/EmptyLiteral:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/EvenOdd:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/GuardClause:
  Enabled: true
Style/IfUnlessModifier:
  Enabled: false
Style/IfWithSemicolon:
  Enabled: false
Style/InlineComment:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/LineEndConcatenation:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/NegatedWhile:
  Enabled: false
Style/Next:
  Enabled: false
Style/NilComparison:
  Enabled: false
Style/Not:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/OneLineConditional:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/PreferredHashMethods:
  Enabled: false
Style/Proc:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/SelfAssignment:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Style/SingleLineMethods:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  EnforcedStyle: brackets
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrivialAccessors:
  Enabled: false
Style/VariableInterpolation:
  Enabled: false
Style/WhenThen:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false
Style/WordArray:
  EnforcedStyle: brackets
